# src/utils/exceptions.py


class CancellationException(Exception):
    """Raised when an operation is cancelled by the user."""
    pass
